project:
  name: __PROJECT_NAME__

runtimes:
  claude:
    enabled: true
  codex:
    enabled: false
  cursor:
    enabled: false
  kiro:
    enabled: false
  opencode:
    enabled: false

sync:
  permissions: true
  # mcp: true

files:
  permissions: .ai/permissions.yaml
  # mcp: .ai/mcp.yaml
