import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { renderCodexConfig, renderCodexHook } from "../src/adapters/codex";
import { CodexSettings, codexDefaults } from "../src/config";
import { Permissions, globToRegexSource } from "../src/permissions";

const p: Permissions = {
  policy: { precedence: "deny_over_allow" },
  filesystem: { edit: "allow", write: "allow" },
  shell: {
    default: "ask",
    allow: ["git*", "pnpm*"],
    deny: ["git push*", "git reset --hard*", "git clean*", "git rm*", "gh pr create*", "gh api*"]
  }
};

test("Codex config uses native sandbox and approval settings", () => {
  assert.match(renderCodexConfig(p), /approval_policy = "on-request"/);
  assert.match(renderCodexConfig(p), /sandbox_mode = "workspace-write"/);
  const readonly = { ...p, filesystem: { edit: "ask" as const, write: "deny" as const } };
  assert.match(renderCodexConfig(readonly), /sandbox_mode = "read-only"/);
});

test("Codex config maps shell.default=allow to auto (not never)", () => {
  const allowAll: Permissions = {
    ...p,
    shell: { default: "allow", allow: [], deny: [] }
  };
  assert.match(renderCodexConfig(allowAll), /approval_policy = "auto"/);
});

test("Codex config maps shell.default=deny to never", () => {
  const denyAll: Permissions = {
    ...p,
    shell: { default: "deny", allow: [], deny: [] }
  };
  assert.match(renderCodexConfig(denyAll), /approval_policy = "never"/);
});

test("glob conversion and generated hook block only dangerous Bash commands", () => {
  assert.equal(globToRegexSource("git push*"), "^git push.*$");
  const dir = mkdtempSync(join(tmpdir(), "agentctl-test-"));
  const hook = join(dir, "policy.py");
  writeFileSync(hook, renderCodexHook(p));
  const denied = [
    "git push",
    "git reset --hard HEAD",
    "git clean -fd",
    "git rm file.txt",
    "gh pr create",
    "gh api"
  ];
  const allowed = ["git status", "git diff", "git add .", 'git commit -m \\"test\\"', "pnpm test"];
  for (const command of denied) {
    const run = spawnSync("python3", [hook], {
      input: JSON.stringify({ tool_name: "Bash", tool_input: { command } }),
      encoding: "utf8"
    });
    assert.equal(JSON.parse(run.stdout).permissionDecision, "deny", command);
  }
  for (const command of allowed) {
    const run = spawnSync("python3", [hook], {
      input: JSON.stringify({ tool_name: "Bash", tool_input: { command } }),
      encoding: "utf8"
    });
    const result = JSON.parse(run.stdout);
    assert.equal(result.permissionDecision, "allow", `expected allow for: ${command}`);
  }
  assert.match(renderCodexHook(p), /@generated by agentctl/);
});

test("Codex hook includes ALLOW_PATTERNS from shell.allow", () => {
  const hook = renderCodexHook(p);
  assert.match(hook, /ALLOW_PATTERNS/);
  // Verify the allow patterns are present as regex sources
  assert.match(hook, /\^git\.\*\$/);
  assert.match(hook, /\^pnpm\.\*\$/);
});

test("Codex hook emits allow decision for matching allow patterns", () => {
  const dir = mkdtempSync(join(tmpdir(), "agentctl-allow-"));
  const hook = join(dir, "policy.py");
  writeFileSync(hook, renderCodexHook(p));
  const allowedByPattern = ["git status", "git diff", "pnpm install", "pnpm test"];
  for (const command of allowedByPattern) {
    const run = spawnSync("python3", [hook], {
      input: JSON.stringify({ tool_name: "Bash", tool_input: { command } }),
      encoding: "utf8"
    });
    const result = JSON.parse(run.stdout);
    assert.equal(result.permissionDecision, "allow", `expected allow for: ${command}`);
  }
});

test("Codex hook deny takes precedence over allow", () => {
  // "git push" matches both "git*" (allow) and "git push*" (deny)
  // deny must win
  const dir = mkdtempSync(join(tmpdir(), "agentctl-precedence-"));
  const hook = join(dir, "policy.py");
  writeFileSync(hook, renderCodexHook(p));
  const run = spawnSync("python3", [hook], {
    input: JSON.stringify({ tool_name: "Bash", tool_input: { command: "git push origin main" } }),
    encoding: "utf8"
  });
  const result = JSON.parse(run.stdout);
  assert.equal(result.permissionDecision, "deny");
});

// --- Filesystem deny enforcement tests ---

test("Codex hook denies file-write commands when filesystem.write is deny", () => {
  const fsWriteDeny: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "deny" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const dir = mkdtempSync(join(tmpdir(), "agentctl-fs-write-"));
  const hook = join(dir, "policy.py");
  writeFileSync(hook, renderCodexHook(fsWriteDeny));

  const writeCommands = [
    "echo hello > output.txt",
    "tee /tmp/file.txt",
    "cp src/a.ts src/b.ts",
    "mv old.txt new.txt",
    "rm -rf build/",
    "mkdir -p /tmp/newdir",
    "chmod 755 script.sh",
    "chown user:group file.txt",
    "ln -s target link",
    "touch newfile.txt"
  ];

  for (const command of writeCommands) {
    const run = spawnSync("python3", [hook], {
      input: JSON.stringify({ tool_name: "Bash", tool_input: { command } }),
      encoding: "utf8"
    });
    const result = JSON.parse(run.stdout);
    assert.equal(result.permissionDecision, "deny", `expected deny for write command: ${command}`);
    assert.match(result.permissionDecisionReason, /filesystem write deny/);
  }
});

test("Codex hook allows file-write commands when filesystem.write is allow", () => {
  const dir = mkdtempSync(join(tmpdir(), "agentctl-fs-allow-"));
  const hook = join(dir, "policy.py");
  // p has filesystem.write = "allow" so write commands should NOT be blocked by fs policy
  writeFileSync(hook, renderCodexHook(p));

  const writeCommands = ["touch newfile.txt", "mkdir -p /tmp/dir"];
  for (const command of writeCommands) {
    const run = spawnSync("python3", [hook], {
      input: JSON.stringify({ tool_name: "Bash", tool_input: { command } }),
      encoding: "utf8"
    });
    // Should not be denied (no shell deny pattern matches, and fs write is allowed)
    if (run.stdout.trim()) {
      const result = JSON.parse(run.stdout);
      assert.notEqual(
        result.permissionDecision,
        "deny",
        `should not deny write command when fs.write=allow: ${command}`
      );
    }
  }
});

test("Codex hook denies edit-in-place commands when filesystem.edit is deny", () => {
  const fsEditDeny: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "deny", write: "allow" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const dir = mkdtempSync(join(tmpdir(), "agentctl-fs-edit-"));
  const hook = join(dir, "policy.py");
  writeFileSync(hook, renderCodexHook(fsEditDeny));

  const editCommands = [
    "sed -i 's/old/new/g' file.txt",
    "perl -ip -e 's/foo/bar/' file.pl",
    "patch < fix.diff"
  ];

  for (const command of editCommands) {
    const run = spawnSync("python3", [hook], {
      input: JSON.stringify({ tool_name: "Bash", tool_input: { command } }),
      encoding: "utf8"
    });
    const result = JSON.parse(run.stdout);
    assert.equal(result.permissionDecision, "deny", `expected deny for edit command: ${command}`);
    assert.match(result.permissionDecisionReason, /filesystem edit deny/);
  }
});

test("Codex hook does not deny read-only commands when filesystem.write is deny", () => {
  const fsWriteDeny: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "deny" },
    shell: { default: "ask", allow: ["cat*", "ls*", "grep*"], deny: [] }
  };
  const dir = mkdtempSync(join(tmpdir(), "agentctl-fs-read-"));
  const hook = join(dir, "policy.py");
  writeFileSync(hook, renderCodexHook(fsWriteDeny));

  const readCommands = ["cat file.txt", "ls -la", "grep -r pattern ."];
  for (const command of readCommands) {
    const run = spawnSync("python3", [hook], {
      input: JSON.stringify({ tool_name: "Bash", tool_input: { command } }),
      encoding: "utf8"
    });
    if (run.stdout.trim()) {
      const result = JSON.parse(run.stdout);
      assert.equal(result.permissionDecision, "allow", `should allow read command: ${command}`);
    }
  }
});

test("Codex hook shell deny takes precedence over filesystem checks", () => {
  // If a command is in shell deny, it should be denied even if filesystem allows
  const perms: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "allow" },
    shell: { default: "ask", allow: [], deny: ["rm -rf*"] }
  };
  const dir = mkdtempSync(join(tmpdir(), "agentctl-deny-priority-"));
  const hook = join(dir, "policy.py");
  writeFileSync(hook, renderCodexHook(perms));

  const run = spawnSync("python3", [hook], {
    input: JSON.stringify({ tool_name: "Bash", tool_input: { command: "rm -rf /" } }),
    encoding: "utf8"
  });
  const result = JSON.parse(run.stdout);
  assert.equal(result.permissionDecision, "deny");
  assert.match(result.permissionDecisionReason, /shell deny/);
});

// --- notifyOnDeny setting tests ---

test("Codex hook logs to stderr when notifyOnDeny is true", () => {
  const perms: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "deny" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const settings: CodexSettings = { notifyOnDeny: true };
  const dir = mkdtempSync(join(tmpdir(), "agentctl-notify-"));
  const hook = join(dir, "policy.py");
  writeFileSync(hook, renderCodexHook(perms, settings));

  const run = spawnSync("python3", [hook], {
    input: JSON.stringify({ tool_name: "Bash", tool_input: { command: "touch file.txt" } }),
    encoding: "utf8"
  });
  const result = JSON.parse(run.stdout);
  assert.equal(result.permissionDecision, "deny");
  assert.match(run.stderr, /\[agentctl\] denied:/);
});

test("Codex hook does not log to stderr when notifyOnDeny is false (default)", () => {
  const perms: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "deny" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const dir = mkdtempSync(join(tmpdir(), "agentctl-no-notify-"));
  const hook = join(dir, "policy.py");
  writeFileSync(hook, renderCodexHook(perms));

  const run = spawnSync("python3", [hook], {
    input: JSON.stringify({ tool_name: "Bash", tool_input: { command: "touch file.txt" } }),
    encoding: "utf8"
  });
  const result = JSON.parse(run.stdout);
  assert.equal(result.permissionDecision, "deny");
  assert.equal(run.stderr, "");
});

// --- Hook renders FS_WRITE_DENIED / FS_EDIT_DENIED flags ---

test("Codex hook renders FS_WRITE_DENIED = True when filesystem.write is deny", () => {
  const perms: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "deny" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const hook = renderCodexHook(perms);
  assert.match(hook, /FS_WRITE_DENIED = True/);
  assert.match(hook, /FS_EDIT_DENIED = False/);
});

test("Codex hook renders FS_EDIT_DENIED = True when filesystem.edit is deny", () => {
  const perms: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "deny", write: "allow" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const hook = renderCodexHook(perms);
  assert.match(hook, /FS_WRITE_DENIED = False/);
  assert.match(hook, /FS_EDIT_DENIED = True/);
});

test("Codex hook renders both FS flags as False when filesystem is fully allowed", () => {
  const hook = renderCodexHook(p);
  assert.match(hook, /FS_WRITE_DENIED = False/);
  assert.match(hook, /FS_EDIT_DENIED = False/);
});

test("Codex hook renders NOTIFY_ON_DENY = True when notifyOnDeny setting is true", () => {
  const settings: CodexSettings = { notifyOnDeny: true };
  const hook = renderCodexHook(p, settings);
  assert.match(hook, /NOTIFY_ON_DENY = True/);
});

test("Codex hook renders NOTIFY_ON_DENY = False by default", () => {
  const hook = renderCodexHook(p);
  assert.match(hook, /NOTIFY_ON_DENY = False/);
});

// --- codexDefaults ---

test("codexDefaults has notifyOnDeny set to false", () => {
  assert.equal(codexDefaults.notifyOnDeny, false);
});
