import test from "node:test";
import assert from "node:assert/strict";
import { renderCursorRule } from "../src/adapters/cursor";
import { Permissions } from "../src/permissions";

const permissions: Permissions = {
  policy: { precedence: "deny_over_allow" },
  filesystem: { edit: "allow", write: "allow" },
  shell: { default: "ask", allow: ["git *", "pnpm *"], deny: ["git push *"] }
};

test("Cursor renders valid MDC frontmatter with alwaysApply true", () => {
  const output = renderCursorRule(permissions);
  assert.ok(output.startsWith("---\n"), "must start with frontmatter delimiter");
  assert.match(output, /alwaysApply: true/);
  assert.match(output, /description: "Shell and filesystem permissions enforced by agentctl"/);
  // Second delimiter closes frontmatter
  const parts = output.split("---");
  assert.ok(parts.length >= 3, "must have opening and closing frontmatter delimiters");
});

test("Cursor includes filesystem permission values", () => {
  const output = renderCursorRule(permissions);
  assert.match(output, /File editing: allow/);
  assert.match(output, /File creation\/write: allow/);
});

test("Cursor includes deny patterns as a list", () => {
  const output = renderCursorRule(permissions);
  assert.match(output, /### Denied \(never run these\)/);
  assert.match(output, /`git push \*`/);
});

test("Cursor includes allow patterns as a list", () => {
  const output = renderCursorRule(permissions);
  assert.match(output, /### Allowed \(safe to run without asking\)/);
  assert.match(output, /`git \*`/);
  assert.match(output, /`pnpm \*`/);
});

test("Cursor includes the default shell policy", () => {
  const output = renderCursorRule(permissions);
  assert.match(output, /Default policy: ask/);
});

test("Cursor omits deny section when no deny patterns exist", () => {
  const perms: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "allow" },
    shell: { default: "allow", allow: ["git *"], deny: [] }
  };
  const output = renderCursorRule(perms);
  assert.doesNotMatch(output, /### Denied/);
  assert.match(output, /### Allowed/);
});

test("Cursor omits allow section when no allow patterns exist", () => {
  const perms: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "deny", write: "deny" },
    shell: { default: "deny", allow: [], deny: ["rm -rf *"] }
  };
  const output = renderCursorRule(perms);
  assert.match(output, /### Denied/);
  assert.doesNotMatch(output, /### Allowed/);
});

test("Cursor renders filesystem deny values correctly", () => {
  const perms: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "deny", write: "ask" },
    shell: { default: "deny", allow: [], deny: [] }
  };
  const output = renderCursorRule(perms);
  assert.match(output, /File editing: deny/);
  assert.match(output, /File creation\/write: ask/);
});

test("Cursor output is deterministic", () => {
  assert.equal(renderCursorRule(permissions), renderCursorRule(permissions));
});

test("Cursor output contains the generated-file warning", () => {
  const output = renderCursorRule(permissions);
  assert.match(output, /generated by agentctl/i);
  assert.match(output, /Do not edit directly/);
});
