import test from "node:test";
import assert from "node:assert/strict";
import { renderOpenCode } from "../src/adapters/opencode";
import { Permissions } from "../src/permissions";
import { McpConfig } from "../src/mcp";

test("OpenCode renders native allow and deny rules with deny entries after broad allows", () => {
  const p: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "allow" },
    shell: { default: "ask", allow: ["git*"], deny: ["git push*", "git reset --hard*"] }
  };
  const permission = JSON.parse(renderOpenCode(p)).permission;
  assert.equal(permission.edit, "allow");
  assert.equal(permission.bash["git*"], "allow");
  assert.equal(permission.bash["git push*"], "deny");
  assert.deepEqual(Object.keys(permission.bash), ["*", "git*", "git push*", "git reset --hard*"]);
});

test("OpenCode renders filesystem permission values", () => {
  const p: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "deny", write: "ask" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const parsed = JSON.parse(renderOpenCode(p));
  assert.equal(parsed.permission.edit, "deny");
  assert.equal(parsed.permission.write, "ask");
});

test("OpenCode includes _generatedBy marker", () => {
  const p: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "allow" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const parsed = JSON.parse(renderOpenCode(p));
  assert.match(parsed._generatedBy, /@generated by agentctl/);
});

// --- MCP server config tests ---

test("OpenCode includes mcpServers when mcp config is provided", () => {
  const p: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "allow" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const mcp: McpConfig = {
    servers: {
      filesystem: {
        transport: "stdio",
        command: "npx",
        args: ["-y", "@modelcontextprotocol/server-filesystem", "/tmp"]
      }
    }
  };
  const parsed = JSON.parse(renderOpenCode(p, mcp));
  assert.ok(parsed.mcpServers, "must include mcpServers");
  assert.equal(Object.keys(parsed.mcpServers).length, 1);
  assert.equal(parsed.mcpServers.filesystem.command, "npx");
  assert.deepEqual(parsed.mcpServers.filesystem.args, [
    "-y",
    "@modelcontextprotocol/server-filesystem",
    "/tmp"
  ]);
});

test("OpenCode omits mcpServers when mcp config is undefined", () => {
  const p: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "allow" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const parsed = JSON.parse(renderOpenCode(p));
  assert.equal(parsed.mcpServers, undefined);
});

test("OpenCode renders streamable-http server with url", () => {
  const p: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "allow" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const mcp: McpConfig = {
    servers: {
      "my-api": {
        transport: "streamable-http",
        url: "http://localhost:3001/mcp"
      }
    }
  };
  const parsed = JSON.parse(renderOpenCode(p, mcp));
  assert.equal(parsed.mcpServers["my-api"].url, "http://localhost:3001/mcp");
  assert.equal(parsed.mcpServers["my-api"].command, undefined);
});

test("OpenCode includes env in MCP server when present", () => {
  const p: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "allow" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const mcp: McpConfig = {
    servers: {
      github: {
        transport: "stdio",
        command: "docker",
        args: ["run", "-i", "ghcr.io/github/github-mcp-server"],
        env: { GITHUB_TOKEN: "${GITHUB_TOKEN}" }
      }
    }
  };
  const parsed = JSON.parse(renderOpenCode(p, mcp));
  assert.deepEqual(parsed.mcpServers.github.env, { GITHUB_TOKEN: "${GITHUB_TOKEN}" });
});

test("OpenCode omits env from MCP server when not present", () => {
  const p: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "allow" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const mcp: McpConfig = {
    servers: {
      simple: {
        transport: "stdio",
        command: "my-server"
      }
    }
  };
  const parsed = JSON.parse(renderOpenCode(p, mcp));
  assert.equal(parsed.mcpServers.simple.env, undefined);
});

test("OpenCode omits args from MCP server when empty", () => {
  const p: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "allow" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const mcp: McpConfig = {
    servers: {
      simple: {
        transport: "stdio",
        command: "my-server",
        args: []
      }
    }
  };
  const parsed = JSON.parse(renderOpenCode(p, mcp));
  assert.equal(parsed.mcpServers.simple.args, undefined);
});

test("OpenCode renders multiple MCP servers", () => {
  const p: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "allow" },
    shell: { default: "ask", allow: [], deny: [] }
  };
  const mcp: McpConfig = {
    servers: {
      filesystem: {
        transport: "stdio",
        command: "npx",
        args: ["-y", "@modelcontextprotocol/server-filesystem"]
      },
      "my-api": {
        transport: "streamable-http",
        url: "http://localhost:3001/mcp"
      }
    }
  };
  const parsed = JSON.parse(renderOpenCode(p, mcp));
  assert.equal(Object.keys(parsed.mcpServers).length, 2);
  assert.equal(parsed.mcpServers.filesystem.command, "npx");
  assert.equal(parsed.mcpServers["my-api"].url, "http://localhost:3001/mcp");
});

test("OpenCode output is deterministic", () => {
  const p: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: "allow", write: "allow" },
    shell: { default: "ask", allow: ["git*"], deny: ["git push*"] }
  };
  const mcp: McpConfig = {
    servers: {
      filesystem: {
        transport: "stdio",
        command: "npx",
        args: ["-y", "server"]
      }
    }
  };
  assert.equal(renderOpenCode(p, mcp), renderOpenCode(p, mcp));
});
