import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, writeFileSync, mkdirSync, rmSync, existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { scan, regexSourceToGlob, isGeneratedFile } from "../src/scan";
import { GENERATED_MARKER } from "../src/permissions";

const PROJECT_ROOT = resolve(__dirname, "..", "..");
const CLI = resolve(PROJECT_ROOT, "src", "cli.ts");
const TSX = resolve(PROJECT_ROOT, "node_modules", ".bin", "tsx");

function runScan(
  cwd: string,
  args: string[] = []
): { stdout: string; stderr: string; exitCode: number } {
  const result = spawnSync(TSX, [CLI, "scan", ...args], {
    cwd,
    encoding: "utf8",
    env: { ...process.env, NODE_NO_WARNINGS: "1" }
  });
  return { stdout: result.stdout, stderr: result.stderr, exitCode: result.status ?? 1 };
}

function makeTmpDir(): string {
  return mkdtempSync(join(tmpdir(), "agentctl-scan-"));
}

function writeClaude(root: string, allow: string[], deny: string[]): void {
  const settings = {
    $schema: "https://json.schemastore.org/claude-code-settings.json",
    permissions: {
      allow: ["Edit", "Write", ...allow.map((p) => `Bash(${p})`)],
      deny: deny.map((p) => `Bash(${p})`)
    }
  };
  mkdirSync(join(root, ".claude"), { recursive: true });
  writeFileSync(join(root, ".claude", "settings.json"), JSON.stringify(settings, null, 2), "utf8");
}

function writeClaudeRaw(root: string, content: string): void {
  mkdirSync(join(root, ".claude"), { recursive: true });
  writeFileSync(join(root, ".claude", "settings.json"), content, "utf8");
}

function writeCodexToml(root: string, policy: string): void {
  const toml = `approval_policy = "${policy}"\nsandbox_mode = "workspace-write"\n`;
  mkdirSync(join(root, ".codex"), { recursive: true });
  writeFileSync(join(root, ".codex", "config.toml"), toml, "utf8");
}

function writeCodexHook(root: string, allow: string[], deny: string[]): void {
  const allowRegex = allow.map((g) => `^${g.replace(/\*/g, ".*")}$`);
  const denyRegex = deny.map((g) => `^${g.replace(/\*/g, ".*")}$`);
  const hook = `#!/usr/bin/env python3
DENY_PATTERNS = ${JSON.stringify(denyRegex, null, 2)}

ALLOW_PATTERNS = ${JSON.stringify(allowRegex, null, 2)}

def main():
    pass
`;
  mkdirSync(join(root, ".codex", "hooks"), { recursive: true });
  writeFileSync(join(root, ".codex", "hooks", "permission-policy.py"), hook, "utf8");
}

function writeCodexJson(root: string, policy: string, allow: string[], deny: string[]): void {
  const config = {
    approval_policy: policy,
    shell: { allow, deny }
  };
  writeFileSync(join(root, "codex.json"), JSON.stringify(config, null, 2), "utf8");
}

function writeKiro(
  root: string,
  rules: Array<{ capability: string; effect: string; match?: string[] }>
): void {
  const { stringify } = require("yaml");
  const content = stringify({ rules });
  mkdirSync(join(root, ".kiro", "settings"), { recursive: true });
  writeFileSync(join(root, ".kiro", "settings", "permissions.yaml"), content, "utf8");
}

function writeOpenCode(
  root: string,
  permission: { edit?: string; write?: string; bash?: Record<string, string> }
): void {
  const config = { permission };
  mkdirSync(join(root, ".opencode"), { recursive: true });
  writeFileSync(join(root, ".opencode", "opencode.json"), JSON.stringify(config, null, 2), "utf8");
}

function writeCursorRule(
  root: string,
  opts: { shell?: string; edit?: string; write?: string; deny?: string[]; allow?: string[] }
): void {
  const lines: string[] = [];
  lines.push("---");
  lines.push('description: "Shell and filesystem permissions enforced by agentctl"');
  lines.push("alwaysApply: true");
  lines.push("---");
  lines.push("");
  lines.push("# Permissions Policy");
  lines.push("");
  lines.push("This rule is generated by agentctl. Do not edit directly.");
  lines.push("");
  lines.push("## Filesystem");
  lines.push("");
  lines.push(`- File editing: ${opts.edit ?? "allow"}`);
  lines.push(`- File creation/write: ${opts.write ?? "allow"}`);
  lines.push("");
  lines.push("## Shell Commands");
  lines.push("");
  lines.push(`Default policy: ${opts.shell ?? "ask"}`);
  lines.push("");
  if (opts.deny && opts.deny.length > 0) {
    lines.push("### Denied (never run these)");
    lines.push("");
    for (const p of opts.deny) lines.push(`- \`${p}\``);
    lines.push("");
  }
  if (opts.allow && opts.allow.length > 0) {
    lines.push("### Allowed (safe to run without asking)");
    lines.push("");
    for (const p of opts.allow) lines.push(`- \`${p}\``);
    lines.push("");
  }
  const dir = join(root, ".cursor", "rules", "agentctl-permissions");
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "RULE.md"), lines.join("\n"), "utf8");
}

// --- Unit tests for regexSourceToGlob ---

test("regexSourceToGlob converts simple anchored regex back to glob", () => {
  assert.equal(regexSourceToGlob("^git .*$"), "git *");
  assert.equal(regexSourceToGlob("^pnpm .*$"), "pnpm *");
  assert.equal(regexSourceToGlob("^rm -rf .*$"), "rm -rf *");
});

test("regexSourceToGlob converts .+ to *", () => {
  assert.equal(regexSourceToGlob("^npm .+$"), "npm *");
});

test("regexSourceToGlob unescapes common chars", () => {
  assert.equal(regexSourceToGlob("^git\\.status$"), "git.status");
});

test("regexSourceToGlob flags complex patterns with regex marker", () => {
  const result = regexSourceToGlob("^(git|svn) .*$");
  assert.ok(result.includes("# regex:"), "Should contain regex comment marker");
  assert.ok(result.includes("^(git|svn) .*$"), "Should include original source");
});

test("regexSourceToGlob flags character classes with regex marker", () => {
  const result = regexSourceToGlob("^[a-z]+ .*$");
  assert.ok(result.includes("# regex:"), "Should contain regex comment marker");
});

test("regexSourceToGlob flags look-ahead patterns with regex marker", () => {
  const result = regexSourceToGlob("^(?!rm).*$");
  assert.ok(result.includes("# regex:"), "Should contain regex comment marker");
});

// --- Unit tests for isGeneratedFile ---

test("isGeneratedFile detects canonical GENERATED_MARKER", () => {
  assert.equal(isGeneratedFile(`# ${GENERATED_MARKER}\nrules:\n  - capability: shell`), true);
});

test("isGeneratedFile detects marker in JSON _generatedBy field", () => {
  const content = JSON.stringify({ _generatedBy: GENERATED_MARKER, permission: {} });
  assert.equal(isGeneratedFile(content), true);
});

test("isGeneratedFile detects legacy 'Generated by: agentctl'", () => {
  assert.equal(isGeneratedFile("# Generated by: agentctl\nimport json"), true);
});

test("isGeneratedFile detects legacy 'generated by agentctl'", () => {
  assert.equal(isGeneratedFile("This rule is generated by agentctl. Do not edit."), true);
});

test("isGeneratedFile returns false for non-generated content", () => {
  assert.equal(isGeneratedFile('{"permissions": {"allow": ["Bash(git *)"]}}'), false);
});

test("isGeneratedFile returns false for plain yaml", () => {
  assert.equal(isGeneratedFile("rules:\n  - capability: shell\n    effect: allow"), false);
});

// --- Unit tests for scan() with Claude ---

test("scan detects .claude/settings.json and extracts Bash patterns", async () => {
  const root = makeTmpDir();
  try {
    writeClaude(root, ["git *", "pnpm *"], ["rm -rf *"]);
    const result = await scan(root);
    assert.equal(result.detected.length, 1);
    assert.equal(result.detected[0].name, "claude");
    assert.deepEqual(result.detected[0].allowPatterns, ["git *", "pnpm *"]);
    assert.deepEqual(result.detected[0].denyPatterns, ["rm -rf *"]);
    assert.equal(result.detected[0].shell, "ask");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan extracts filesystem permissions from Claude Edit/Write entries", async () => {
  const root = makeTmpDir();
  try {
    writeClaude(root, ["git *"], []);
    const result = await scan(root);
    assert.equal(result.detected[0].filesystem?.edit, "allow");
    assert.equal(result.detected[0].filesystem?.write, "allow");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan derives filesystem ask when Claude has no Edit/Write", async () => {
  const root = makeTmpDir();
  try {
    // Write Claude settings without Edit/Write in allow
    writeClaudeRaw(
      root,
      JSON.stringify({
        permissions: {
          allow: ["Bash(git *)"],
          deny: []
        }
      })
    );
    const result = await scan(root);
    assert.equal(result.detected[0].filesystem?.edit, "ask");
    assert.equal(result.detected[0].filesystem?.write, "ask");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// --- Unit tests for scan() with Codex ---

test("scan detects .codex/config.toml and extracts approval policy", async () => {
  const root = makeTmpDir();
  try {
    writeCodexToml(root, "auto");
    const result = await scan(root);
    assert.equal(result.detected.length, 1);
    assert.equal(result.detected[0].name, "codex");
    assert.equal(result.detected[0].shell, "allow");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan detects codex.json when .codex/config.toml is absent", async () => {
  const root = makeTmpDir();
  try {
    writeCodexJson(root, "on-request", ["npm test"], ["curl *"]);
    const result = await scan(root);
    assert.equal(result.detected.length, 1);
    assert.equal(result.detected[0].name, "codex");
    assert.equal(result.detected[0].path, "codex.json");
    assert.equal(result.detected[0].shell, "ask");
    assert.deepEqual(result.detected[0].allowPatterns, ["npm test"]);
    assert.deepEqual(result.detected[0].denyPatterns, ["curl *"]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan prefers .codex/config.toml over codex.json", async () => {
  const root = makeTmpDir();
  try {
    writeCodexToml(root, "never");
    writeCodexJson(root, "auto", ["echo *"], []);
    const result = await scan(root);
    assert.equal(result.detected.length, 1);
    assert.equal(result.detected[0].path, ".codex/config.toml");
    assert.equal(result.detected[0].shell, "deny");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan reads codex hook patterns and converts regex back to globs", async () => {
  const root = makeTmpDir();
  try {
    writeCodexToml(root, "on-request");
    writeCodexHook(root, ["pnpm *", "git status"], ["rm -rf *"]);
    const result = await scan(root);
    assert.equal(result.detected.length, 1);
    assert.deepEqual(result.detected[0].allowPatterns, ["pnpm *", "git status"]);
    assert.deepEqual(result.detected[0].denyPatterns, ["rm -rf *"]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// --- Unit tests for scan() with Kiro ---

test("scan detects .kiro/settings/permissions.yaml and extracts shell patterns", async () => {
  const root = makeTmpDir();
  try {
    writeKiro(root, [
      { capability: "fs_read", effect: "allow", match: ["**"] },
      { capability: "fs_write", effect: "allow", match: ["**"] },
      { capability: "shell", effect: "deny", match: ["rm -rf *", "curl *"] },
      { capability: "shell", effect: "allow", match: ["git *", "pnpm *"] },
      { capability: "shell", effect: "ask" }
    ]);
    const result = await scan(root);
    assert.equal(result.detected.length, 1);
    assert.equal(result.detected[0].name, "kiro");
    assert.equal(result.detected[0].shell, "ask");
    assert.deepEqual(result.detected[0].allowPatterns, ["git *", "pnpm *"]);
    assert.deepEqual(result.detected[0].denyPatterns, ["rm -rf *", "curl *"]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan extracts filesystem permissions from Kiro fs_write rule", async () => {
  const root = makeTmpDir();
  try {
    writeKiro(root, [
      { capability: "fs_write", effect: "deny", match: ["**"] },
      { capability: "shell", effect: "allow" }
    ]);
    const result = await scan(root);
    assert.equal(result.detected[0].filesystem?.write, "deny");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan handles Kiro catch-all with ** match as shell default", async () => {
  const root = makeTmpDir();
  try {
    writeKiro(root, [
      { capability: "shell", effect: "deny", match: ["rm *"] },
      { capability: "shell", effect: "allow", match: ["**"] }
    ]);
    const result = await scan(root);
    assert.equal(result.detected[0].shell, "allow");
    assert.deepEqual(result.detected[0].denyPatterns, ["rm *"]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// --- Unit tests for scan() with OpenCode ---

test("scan detects .opencode/opencode.json and extracts permission map", async () => {
  const root = makeTmpDir();
  try {
    writeOpenCode(root, {
      edit: "allow",
      write: "allow",
      bash: { "*": "ask", "git *": "allow", "pnpm *": "allow", "rm -rf *": "deny" }
    });
    const result = await scan(root);
    assert.equal(result.detected.length, 1);
    assert.equal(result.detected[0].name, "opencode");
    assert.equal(result.detected[0].shell, "ask");
    assert.deepEqual(result.detected[0].allowPatterns.sort(), ["git *", "pnpm *"]);
    assert.deepEqual(result.detected[0].denyPatterns, ["rm -rf *"]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan extracts filesystem permissions from OpenCode", async () => {
  const root = makeTmpDir();
  try {
    writeOpenCode(root, { edit: "ask", write: "deny", bash: { "*": "allow" } });
    const result = await scan(root);
    assert.equal(result.detected[0].filesystem?.edit, "ask");
    assert.equal(result.detected[0].filesystem?.write, "deny");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan handles OpenCode with only bash permissions", async () => {
  const root = makeTmpDir();
  try {
    writeOpenCode(root, { bash: { "*": "deny", "echo *": "allow" } });
    const result = await scan(root);
    assert.equal(result.detected[0].shell, "deny");
    assert.deepEqual(result.detected[0].allowPatterns, ["echo *"]);
    assert.equal(result.detected[0].filesystem?.edit, undefined);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// --- Unit tests for scan() with Cursor ---

test("scan detects Cursor rule and extracts permissions", async () => {
  const root = makeTmpDir();
  try {
    writeCursorRule(root, {
      shell: "ask",
      edit: "allow",
      write: "allow",
      deny: ["rm -rf *", "curl *"],
      allow: ["git *", "pnpm *"]
    });
    const result = await scan(root);
    assert.equal(result.detected.length, 1);
    assert.equal(result.detected[0].name, "cursor");
    assert.equal(result.detected[0].shell, "ask");
    assert.deepEqual(result.detected[0].allowPatterns, ["git *", "pnpm *"]);
    assert.deepEqual(result.detected[0].denyPatterns, ["rm -rf *", "curl *"]);
    assert.equal(result.detected[0].filesystem?.edit, "allow");
    assert.equal(result.detected[0].filesystem?.write, "allow");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan extracts Cursor filesystem deny", async () => {
  const root = makeTmpDir();
  try {
    writeCursorRule(root, { shell: "deny", edit: "deny", write: "deny" });
    const result = await scan(root);
    assert.equal(result.detected[0].filesystem?.edit, "deny");
    assert.equal(result.detected[0].filesystem?.write, "deny");
    assert.equal(result.detected[0].shell, "deny");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// --- Merge and conflict tests ---

test("scan merges patterns from multiple runtimes with deduplication", async () => {
  const root = makeTmpDir();
  try {
    writeClaude(root, ["git *", "pnpm *"], ["rm -rf *"]);
    writeCodexToml(root, "auto");
    writeCodexHook(root, ["pnpm *", "npm test"], ["rm -rf *", "curl *"]);
    const result = await scan(root);
    assert.equal(result.detected.length, 2);
    // Check merged patterns have no duplicates
    const { permissionsYaml } = result;
    assert.ok(permissionsYaml.includes("git *"));
    assert.ok(permissionsYaml.includes("pnpm *"));
    assert.ok(permissionsYaml.includes("npm test"));
    assert.ok(permissionsYaml.includes("rm -rf *"));
    assert.ok(permissionsYaml.includes("curl *"));
    // "pnpm *" appears only once even though both runtimes have it
    const pnpmMatches = permissionsYaml.match(/pnpm \*/g);
    assert.equal(pnpmMatches?.length, 1);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan reports shell mode conflicts between runtimes", async () => {
  const root = makeTmpDir();
  try {
    writeClaude(root, ["git *"], []);
    writeCodexToml(root, "auto"); // "allow" vs Claude's "ask"
    const result = await scan(root);
    assert.equal(result.conflicts.length, 1);
    assert.equal(result.conflicts[0].field, "shell.default");
    assert.equal(result.conflicts[0].resolved, "ask"); // ask is more restrictive than allow
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan resolves conflict with most restrictive mode (deny > ask > allow)", async () => {
  const root = makeTmpDir();
  try {
    writeClaude(root, [], []);
    writeCodexToml(root, "never"); // "deny" vs Claude's "ask"
    const result = await scan(root);
    assert.equal(result.conflicts.length, 1);
    assert.equal(result.conflicts[0].resolved, "deny");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan derives filesystem permissions from source configs (not hardcoded)", async () => {
  const root = makeTmpDir();
  try {
    // Claude with Edit allowed, Write allowed
    writeClaude(root, ["git *"], []);
    // OpenCode with write: deny
    writeOpenCode(root, { edit: "allow", write: "deny", bash: { "*": "ask" } });
    const result = await scan(root);
    // Most restrictive wins: allow vs allow = allow (edit), allow vs deny = deny (write)
    assert.ok(result.permissionsYaml.includes("edit: allow"));
    assert.ok(result.permissionsYaml.includes("write: deny"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan reports filesystem conflicts", async () => {
  const root = makeTmpDir();
  try {
    writeClaude(root, ["git *"], []); // edit: allow, write: allow
    writeOpenCode(root, { edit: "deny", write: "allow", bash: { "*": "ask" } });
    const result = await scan(root);
    const editConflict = result.conflicts.find((c) => c.field === "filesystem.edit");
    assert.ok(editConflict, "Should have filesystem.edit conflict");
    assert.equal(editConflict!.resolved, "deny");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan returns empty result when no configs are found", async () => {
  const root = makeTmpDir();
  try {
    const result = await scan(root);
    assert.equal(result.detected.length, 0);
    assert.equal(result.configYaml, "");
    assert.equal(result.permissionsYaml, "");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan generates valid config.yaml with detected runtimes enabled", async () => {
  const root = makeTmpDir();
  try {
    writeClaude(root, ["git *"], []);
    writeCodexToml(root, "on-request");
    writeKiro(root, [{ capability: "shell", effect: "ask" }]);
    const result = await scan(root);
    assert.ok(result.configYaml.includes("claude:"));
    assert.ok(result.configYaml.includes("codex:"));
    assert.ok(result.configYaml.includes("kiro:"));
    // Check enabled states
    assert.ok(result.configYaml.includes("cursor:"));
    assert.ok(result.configYaml.includes("opencode:"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan enables cursor runtime when detected", async () => {
  const root = makeTmpDir();
  try {
    writeCursorRule(root, { shell: "ask", allow: ["git *"] });
    const result = await scan(root);
    assert.ok(result.configYaml.includes("cursor:"));
    assert.equal(result.detected[0].name, "cursor");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// --- Generated file detection tests ---

test("scan warns when scanning agentctl-generated Claude settings", async () => {
  const root = makeTmpDir();
  try {
    // Write a file that looks generated (contains the canonical marker)
    writeClaudeRaw(
      root,
      JSON.stringify(
        {
          _generatedBy: GENERATED_MARKER,
          $schema: "https://json.schemastore.org/claude-code-settings.json",
          permissions: { allow: ["Bash(git *)"], deny: [] }
        },
        null,
        2
      )
    );
    const result = await scan(root);
    assert.ok(result.warnings.length > 0);
    assert.ok(result.warnings[0].includes("generated by agentctl"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan warns when scanning generated Cursor rule", async () => {
  const root = makeTmpDir();
  try {
    writeCursorRule(root, { shell: "ask", allow: ["git *"] }); // Contains "generated by agentctl"
    const result = await scan(root);
    assert.ok(result.warnings.length > 0);
    assert.ok(result.warnings[0].includes("cursor"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("scan does not warn for non-generated configs", async () => {
  const root = makeTmpDir();
  try {
    writeClaudeRaw(
      root,
      JSON.stringify({
        permissions: { allow: ["Bash(git *)"], deny: [] }
      })
    );
    const result = await scan(root);
    assert.equal(result.warnings.length, 0);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// --- Multi-runtime scan tests ---

test("scan detects all five runtimes simultaneously", async () => {
  const root = makeTmpDir();
  try {
    writeClaudeRaw(
      root,
      JSON.stringify({
        permissions: { allow: ["Edit", "Write", "Bash(git *)"], deny: [] }
      })
    );
    writeCodexToml(root, "on-request");
    writeCursorRule(root, { shell: "ask", edit: "allow", write: "allow", allow: ["npm *"] });
    writeKiro(root, [
      { capability: "fs_write", effect: "allow", match: ["**"] },
      { capability: "shell", effect: "allow", match: ["pnpm *"] },
      { capability: "shell", effect: "ask" }
    ]);
    writeOpenCode(root, { edit: "allow", write: "allow", bash: { "*": "ask", "yarn *": "allow" } });

    const result = await scan(root);
    assert.equal(result.detected.length, 5);
    const names = result.detected.map((d) => d.name).sort();
    assert.deepEqual(names, ["claude", "codex", "cursor", "kiro", "opencode"]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// --- CLI integration tests ---

test("CLI scan --dry-run prints config without writing files", () => {
  const root = makeTmpDir();
  try {
    writeClaude(root, ["git *", "pnpm test"], ["rm -rf *"]);
    const { stdout, exitCode } = runScan(root, ["--dry-run"]);
    assert.equal(exitCode, 0);
    assert.ok(stdout.includes("Detected runtimes:"));
    assert.ok(stdout.includes(".claude/settings.json"));
    assert.ok(stdout.includes("--- .ai/config.yaml ---"));
    assert.ok(stdout.includes("--- .ai/permissions.yaml ---"));
    // Should NOT create .ai directory
    assert.ok(!existsSync(join(root, ".ai")));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("CLI scan writes .ai/ files when no existing .ai/ directory", () => {
  const root = makeTmpDir();
  try {
    writeClaude(root, ["git *"], ["rm -rf *"]);
    const { stdout, exitCode } = runScan(root);
    assert.equal(exitCode, 0);
    assert.ok(stdout.includes("Generated:"));
    assert.ok(stdout.includes(".ai/config.yaml"));
    assert.ok(stdout.includes(".ai/permissions.yaml"));
    // Verify files exist
    assert.ok(existsSync(join(root, ".ai", "config.yaml")));
    assert.ok(existsSync(join(root, ".ai", "permissions.yaml")));
    // Verify content
    const config = readFileSync(join(root, ".ai", "config.yaml"), "utf8");
    assert.ok(config.includes("claude:"));
    const perms = readFileSync(join(root, ".ai", "permissions.yaml"), "utf8");
    assert.ok(perms.includes("deny_over_allow"));
    assert.ok(perms.includes("git *"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("CLI scan refuses to overwrite existing .ai/ without --force", () => {
  const root = makeTmpDir();
  try {
    writeClaude(root, ["git *"], []);
    mkdirSync(join(root, ".ai"), { recursive: true });
    writeFileSync(join(root, ".ai", "config.yaml"), "existing: true", "utf8");
    const { stderr, exitCode } = runScan(root);
    assert.equal(exitCode, 1);
    assert.ok(stderr.includes("already exists"));
    // Verify original file is untouched
    const content = readFileSync(join(root, ".ai", "config.yaml"), "utf8");
    assert.equal(content, "existing: true");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("CLI scan --force overwrites existing .ai/ files", () => {
  const root = makeTmpDir();
  try {
    writeClaude(root, ["git *"], ["rm -rf *"]);
    mkdirSync(join(root, ".ai"), { recursive: true });
    writeFileSync(join(root, ".ai", "config.yaml"), "existing: true", "utf8");
    const { stdout, exitCode } = runScan(root, ["--force"]);
    assert.equal(exitCode, 0);
    assert.ok(stdout.includes("Generated:"));
    // Verify file was overwritten
    const content = readFileSync(join(root, ".ai", "config.yaml"), "utf8");
    assert.ok(content.includes("claude:"));
    assert.notEqual(content, "existing: true");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("CLI scan prints conflict warnings", () => {
  const root = makeTmpDir();
  try {
    writeClaude(root, ["git *"], []);
    writeCodexToml(root, "auto");
    const { stdout, exitCode } = runScan(root, ["--dry-run"]);
    assert.equal(exitCode, 0);
    assert.ok(stdout.includes("⚠ Conflict:"));
    assert.ok(stdout.includes("ask"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("CLI scan prints generated file warnings", () => {
  const root = makeTmpDir();
  try {
    writeCursorRule(root, { shell: "ask", allow: ["git *"] });
    const { stdout, exitCode } = runScan(root, ["--dry-run"]);
    assert.equal(exitCode, 0);
    assert.ok(stdout.includes("⚠ Warning:"));
    assert.ok(stdout.includes("redundant"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("CLI scan prints nothing-found message when no configs exist", () => {
  const root = makeTmpDir();
  try {
    const { stdout, exitCode } = runScan(root);
    assert.equal(exitCode, 0);
    assert.ok(stdout.includes("No runtime configurations detected"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("CLI scan uses project name from package.json", () => {
  const root = makeTmpDir();
  try {
    writeFileSync(join(root, "package.json"), JSON.stringify({ name: "my-app" }), "utf8");
    writeClaude(root, ["git *"], []);
    const { stdout, exitCode } = runScan(root, ["--dry-run"]);
    assert.equal(exitCode, 0);
    assert.ok(stdout.includes("my-app"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
