import { Permissions, globToRegexSource } from "../permissions";

export function renderCodexConfig(permissions: Permissions): string {
  const writable = permissions.filesystem.edit === "allow" || permissions.filesystem.write === "allow";
  const approval = permissions.shell.default === "ask" ? "on-request" : permissions.shell.default === "deny" ? "never" : "never";
  return `approval_policy = "${approval}"\nsandbox_mode = "${writable ? "workspace-write" : "read-only"}"\n\n[hooks.PreToolUse]\nBash = ".codex/hooks/permission-policy.py"\n`;
}

export function renderCodexHook(permissions: Permissions): string {
  const patterns = permissions.shell.deny.map(globToRegexSource);
  return `#!/usr/bin/env python3
# GENERATED FILE — DO NOT EDIT.
# Source: .ai/permissions.yaml
# Generated by: agentctl
import json
import re
import sys

DENY_PATTERNS = ${JSON.stringify(patterns, null, 2)}

def main() -> None:
    try:
        invocation = json.load(sys.stdin)
    except json.JSONDecodeError:
        return
    if invocation.get("tool_name") != "Bash":
        return
    command = invocation.get("tool_input", {}).get("command", "")
    if any(re.match(pattern, command) for pattern in DENY_PATTERNS):
        print(json.dumps({"permissionDecision": "deny", "permissionDecisionReason": "Blocked by agentctl shell deny policy"}))

if __name__ == "__main__":
    main()
`;
}
