import { Permissions } from "../permissions";
import { McpConfig } from "../mcp";

/** Renders MCP server config as JSON for a standard mcpServers format. */
function renderMcpServers(mcp: McpConfig): Record<string, Record<string, unknown>> {
  const mcpServers: Record<string, Record<string, unknown>> = {};
  for (const [name, server] of Object.entries(mcp.servers)) {
    const entry: Record<string, unknown> = {};
    if (server.transport === "stdio") {
      entry.command = server.command;
      if (server.args && server.args.length > 0) entry.args = server.args;
    } else {
      entry.url = server.url;
    }
    if (server.env && Object.keys(server.env).length > 0) entry.env = server.env;
    mcpServers[name] = entry;
  }
  return mcpServers;
}

/** Renders `.cursor/mcp.json` from MCP config. */
export function renderCursorMcp(mcp: McpConfig): string {
  return `${JSON.stringify({ mcpServers: renderMcpServers(mcp) }, null, 2)}\n`;
}

/**
 * Renders a Cursor project rule (MDC format) that encodes agentctl's
 * permissions as AI instructions.
 *
 * Cursor does not have a native permissions enforcement API — rules are
 * advisory instructions included in the model context. This adapter
 * translates deny/allow/default shell patterns into a clear, always-applied
 * rule so the Cursor agent respects the project's policy.
 *
 * Output: content for `.cursor/rules/agentctl-permissions/RULE.md`
 */
export function renderCursorRule(permissions: Permissions): string {
  const lines: string[] = [];

  // --- Frontmatter ---
  lines.push("---");
  lines.push('description: "Shell and filesystem permissions enforced by agentctl"');
  lines.push("alwaysApply: true");
  lines.push("---");
  lines.push("");

  // --- Header ---
  lines.push("# Permissions Policy");
  lines.push("");
  lines.push("This rule is generated by agentctl. Do not edit directly.");
  lines.push("");

  // --- Filesystem ---
  lines.push("## Filesystem");
  lines.push("");
  lines.push(`- File editing: ${permissions.filesystem.edit}`);
  lines.push(`- File creation/write: ${permissions.filesystem.write}`);
  lines.push("");

  // --- Shell ---
  lines.push("## Shell Commands");
  lines.push("");
  lines.push(`Default policy: ${permissions.shell.default}`);
  lines.push("");

  if (permissions.shell.deny.length > 0) {
    lines.push("### Denied (never run these)");
    lines.push("");
    for (const pattern of permissions.shell.deny) {
      lines.push(`- \`${pattern}\``);
    }
    lines.push("");
  }

  if (permissions.shell.allow.length > 0) {
    lines.push("### Allowed (safe to run without asking)");
    lines.push("");
    for (const pattern of permissions.shell.allow) {
      lines.push(`- \`${pattern}\``);
    }
    lines.push("");
  }

  return lines.join("\n");
}
