import { Permissions } from "../permissions";

/**
 * Renders a Cursor project rule (MDC format) that encodes agentctl's
 * permissions as AI instructions.
 *
 * Cursor does not have a native permissions enforcement API — rules are
 * advisory instructions included in the model context. This adapter
 * translates deny/allow/default shell patterns into a clear, always-applied
 * rule so the Cursor agent respects the project's policy.
 *
 * Output: content for `.cursor/rules/agentctl-permissions/RULE.md`
 */
export function renderCursorRule(permissions: Permissions): string {
  const lines: string[] = [];

  // --- Frontmatter ---
  lines.push("---");
  lines.push('description: "Shell and filesystem permissions enforced by agentctl"');
  lines.push("alwaysApply: true");
  lines.push("---");
  lines.push("");

  // --- Header ---
  lines.push("# Permissions Policy");
  lines.push("");
  lines.push("This rule is generated by agentctl. Do not edit directly.");
  lines.push("");

  // --- Filesystem ---
  lines.push("## Filesystem");
  lines.push("");
  lines.push(`- File editing: ${permissions.filesystem.edit}`);
  lines.push(`- File creation/write: ${permissions.filesystem.write}`);
  lines.push("");

  // --- Shell ---
  lines.push("## Shell Commands");
  lines.push("");
  lines.push(`Default policy: ${permissions.shell.default}`);
  lines.push("");

  if (permissions.shell.deny.length > 0) {
    lines.push("### Denied (never run these)");
    lines.push("");
    for (const pattern of permissions.shell.deny) {
      lines.push(`- \`${pattern}\``);
    }
    lines.push("");
  }

  if (permissions.shell.allow.length > 0) {
    lines.push("### Allowed (safe to run without asking)");
    lines.push("");
    for (const pattern of permissions.shell.allow) {
      lines.push(`- \`${pattern}\``);
    }
    lines.push("");
  }

  return lines.join("\n");
}
