/** Canonical marker embedded in all generated files for detection by `agentctl scan`. */
export const GENERATED_MARKER = "@generated by agentctl — DO NOT EDIT";

export type PermissionValue = "allow" | "ask" | "deny";

/** Supported permission schema versions. `1` is the implicit default. */
export type PermissionsVersion = 1 | 2;

/**
 * A capability governed by a `default` decision plus optional glob/pattern
 * lists evaluated under `deny_over_allow` precedence:
 * deny → ask → allow → default.
 *
 * Used by the v2 path-level filesystem, network, env, and mcp sections.
 */
export interface CapabilityPermissions {
  default: PermissionValue;
  allow: string[];
  deny: string[];
  ask: string[];
}

/** Path-level filesystem permissions for a single access mode (read/write). */
export type PathPermissions = CapabilityPermissions;

/** Network access permissions keyed by URL glob patterns. */
export type NetworkPermissions = CapabilityPermissions;

/** Environment variable access permissions keyed by name glob patterns. */
export type EnvPermissions = CapabilityPermissions;

/** MCP tool permissions keyed by `<server>:<tool>` or `<server>:*` patterns. */
export type McpPermissions = CapabilityPermissions;

export interface Permissions {
  /** Schema version. Absent (v1) files parse to `1`. Optional in literals. */
  version?: PermissionsVersion;
  policy: { precedence: "deny_over_allow" };
  /**
   * Filesystem permissions. `edit`/`write` are the v1 blanket scalars and are
   * always present (derived from the v2 `read`/`write` defaults when a v2 file
   * is parsed) so existing adapters keep working. `read`/`write` path objects
   * are only present for v2 files that declare them.
   */
  filesystem: {
    edit: PermissionValue;
    write: PermissionValue;
    read?: PathPermissions;
    writePaths?: PathPermissions;
  };
  shell: { default: PermissionValue; allow: string[]; deny: string[] };
  /** v2: network access control. Absent for v1 files. */
  network?: NetworkPermissions;
  /** v2: environment variable access control. Absent for v1 files. */
  env?: EnvPermissions;
  /** v2: MCP tool access control. Absent for v1 files. */
  mcp?: McpPermissions;
}

const values = new Set<PermissionValue>(["allow", "ask", "deny"]);

function asObject(value: unknown, label: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(
      `${label} must be an object.\n  Expected structure:\n    ${label}:\n      <key>: <value>`
    );
  }
  return value as Record<string, unknown>;
}

function permission(value: unknown, label: string): PermissionValue {
  if (typeof value !== "string" || !values.has(value as PermissionValue)) {
    throw new Error(`${label} must be one of: allow, ask, deny (got ${JSON.stringify(value)})`);
  }
  return value as PermissionValue;
}

function patterns(value: unknown, label: string): string[] {
  if (
    !Array.isArray(value) ||
    value.some((item) => typeof item !== "string" || item.length === 0)
  ) {
    throw new Error(
      `${label} must be an array of non-empty strings.\n  Expected structure:\n    ${label.split(".").pop()}:\n      - "pattern/*"`
    );
  }
  const result = value as string[];
  if (new Set(result).size !== result.length)
    throw new Error(`${label} contains duplicate patterns`);
  return result;
}

/**
 * Parses an optional pattern list, defaulting to an empty array when absent.
 */
function optionalPatterns(value: unknown, label: string): string[] {
  return value === undefined ? [] : patterns(value, label);
}

/**
 * Ensures no pattern appears in more than one of allow/deny/ask for a capability.
 */
function assertNoOverlap(capability: CapabilityPermissions, label: string): void {
  const lists: Array<[keyof CapabilityPermissions, string[]]> = [
    ["allow", capability.allow],
    ["deny", capability.deny],
    ["ask", capability.ask]
  ];
  const seen = new Map<string, string>();
  for (const [listName, list] of lists) {
    for (const pattern of list) {
      const existing = seen.get(pattern);
      if (existing && existing !== String(listName)) {
        throw new Error(
          `contradictory ${label} patterns: "${pattern}" appears in both ${existing} and ${String(listName)}`
        );
      }
      seen.set(pattern, String(listName));
    }
  }
}

/**
 * Parses a capability block ({ default, allow?, deny?, ask? }) used by the v2
 * path-level filesystem, network, env, and mcp sections. Each pattern is
 * validated with `validatePattern` when provided.
 */
function capability(
  value: unknown,
  label: string,
  validatePattern?: (pattern: string, label: string) => void
): CapabilityPermissions {
  const obj = asObject(value, label);
  const parsed: CapabilityPermissions = {
    default: permission(obj.default, `${label}.default`),
    allow: optionalPatterns(obj.allow, `${label}.allow`),
    deny: optionalPatterns(obj.deny, `${label}.deny`),
    ask: optionalPatterns(obj.ask, `${label}.ask`)
  };
  if (validatePattern) {
    for (const [listName, list] of [
      ["allow", parsed.allow],
      ["deny", parsed.deny],
      ["ask", parsed.ask]
    ] as const) {
      for (const pattern of list) validatePattern(pattern, `${label}.${listName}`);
    }
  }
  assertNoOverlap(parsed, label);
  return parsed;
}

/**
 * Validates a network URL pattern: it must start with a protocol
 * (`https://`, `http://`) or the `*://` wildcard scheme.
 */
function validateNetworkPattern(pattern: string, label: string): void {
  if (!/^(https?|\*):\/\//.test(pattern)) {
    throw new Error(
      `${label} pattern "${pattern}" must start with a protocol (https://, http://) or *://`
    );
  }
}

/**
 * Validates an env var name pattern: names only, no `=` or values.
 */
function validateEnvPattern(pattern: string, label: string): void {
  if (pattern.includes("=")) {
    throw new Error(`${label} pattern "${pattern}" must be a name only, not contain "="`);
  }
}

/**
 * Validates an MCP pattern: it must be `<server>:<tool>` or `<server>:*`.
 */
function validateMcpPattern(pattern: string, label: string): void {
  if (!/^[^:\s]+:([^:\s]+|\*)$/.test(pattern)) {
    throw new Error(`${label} pattern "${pattern}" must be "<server>:<tool>" or "<server>:*"`);
  }
}

/**
 * Validates and normalizes a runtime-neutral permission configuration.
 *
 * Supports two schema versions, selected by the optional top-level `version`
 * field:
 *
 * - **v1** (no `version`, or `version: 1`): the original blanket
 *   `filesystem.edit`/`filesystem.write` scalars plus `shell`.
 * - **v2** (`version: 2`): adds path-level `filesystem.read`/`filesystem.write`
 *   capability blocks and top-level `network`, `env`, and `mcp` sections. The
 *   v1 scalars `filesystem.edit`/`filesystem.write` remain available (derived
 *   from the v2 `read`/`write` defaults) so existing adapters keep working.
 *
 * Shell `allow` and `deny` patterns default to empty arrays.
 *
 * @param raw - The value to validate as a permission configuration
 * @returns The validated permission configuration
 * @throws If the value has an invalid structure, version, permission, policy precedence, pattern list, or overlapping patterns
 */
export function parsePermissions(raw: unknown): Permissions {
  const root = asObject(raw, "permissions");

  let version: PermissionsVersion = 1;
  if (root.version !== undefined) {
    if (root.version !== 1 && root.version !== 2) {
      throw new Error(`version must be 1 or 2 (got ${JSON.stringify(root.version)})`);
    }
    version = root.version;
  }

  const policy = asObject(root.policy, "policy");
  if (policy.precedence !== "deny_over_allow") {
    throw new Error(
      `policy.precedence must be "deny_over_allow" (got ${JSON.stringify(policy.precedence)})`
    );
  }
  const filesystem = asObject(root.filesystem, "filesystem");
  const shell = asObject(root.shell, "shell");

  // Filesystem: v2 may express read/write as capability blocks. When present,
  // derive the v1 scalars from their `default` so existing adapters still work.
  // The blanket `filesystem.edit`/`filesystem.write` scalars remain accepted.
  let fsRead: PathPermissions | undefined;
  let fsWritePaths: PathPermissions | undefined;
  let editScalar: PermissionValue | undefined;
  let writeScalar: PermissionValue | undefined;

  const readIsBlock = filesystem.read !== undefined && typeof filesystem.read === "object";
  const writeIsBlock = filesystem.write !== undefined && typeof filesystem.write === "object";

  const v2Fields = [
    ...(readIsBlock ? ["filesystem.read capability block"] : []),
    ...(writeIsBlock ? ["filesystem.write capability block"] : []),
    ...(["network", "env", "mcp"] as const).filter((field) => root[field] !== undefined)
  ];
  if (version !== 2 && v2Fields.length > 0) {
    throw new Error(`version: 2 is required for ${v2Fields.join(", ")}`);
  }

  if (readIsBlock) {
    fsRead = capability(filesystem.read, "filesystem.read");
  }
  if (writeIsBlock) {
    fsWritePaths = capability(filesystem.write, "filesystem.write");
  }

  if (typeof filesystem.edit === "string") {
    editScalar = permission(filesystem.edit, "filesystem.edit");
  }
  if (typeof filesystem.read === "string") {
    const readScalar = permission(filesystem.read, "filesystem.read");
    if (editScalar === undefined) editScalar = readScalar;
  }
  if (typeof filesystem.write === "string") {
    writeScalar = permission(filesystem.write, "filesystem.write");
  }

  // Resolve the v1 scalars. Prefer explicit scalars; otherwise fall back to the
  // v2 capability defaults; `read` maps to the legacy `edit` scalar.
  const edit = editScalar ?? fsRead?.default;
  const write = writeScalar ?? fsWritePaths?.default;
  if (edit === undefined) {
    throw new Error("filesystem must define edit (or, in v2, filesystem.read with a default)");
  }
  if (write === undefined) {
    throw new Error("filesystem must define write (or, in v2, filesystem.write with a default)");
  }

  const parsed: Permissions = {
    version,
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit, write },
    shell: {
      default: permission(shell.default, "shell.default"),
      allow: patterns(shell.allow ?? [], "shell.allow"),
      deny: patterns(shell.deny ?? [], "shell.deny")
    }
  };

  if (fsRead) parsed.filesystem.read = fsRead;
  if (fsWritePaths) parsed.filesystem.writePaths = fsWritePaths;

  if (root.network !== undefined) {
    parsed.network = capability(root.network, "network", validateNetworkPattern);
  }
  if (root.env !== undefined) {
    parsed.env = capability(root.env, "env", validateEnvPattern);
  }
  if (root.mcp !== undefined) {
    parsed.mcp = capability(root.mcp, "mcp", validateMcpPattern);
  }

  const overlap = parsed.shell.allow.filter((pattern) => parsed.shell.deny.includes(pattern));
  if (overlap.length)
    throw new Error(`contradictory shell allow/deny patterns: ${overlap.join(", ")}`);
  return parsed;
}

/**
 * A permission overlay applied on top of a base {@link Permissions} for a given
 * environment (e.g. `ci`, `prod`). All fields are optional: only the fields
 * present in the overlay file influence the merge. See {@link mergeOverlay}.
 */
export interface PermissionsOverlay {
  filesystem?: { edit?: PermissionValue; write?: PermissionValue };
  shell?: { default?: PermissionValue; allow?: string[]; deny?: string[] };
}

/**
 * Validates and parses an environment-specific permission overlay.
 *
 * All overlay fields are optional. If provided, the policy precedence must be
 * `deny_over_allow`.
 *
 * @param raw - The value to validate as a permission overlay
 * @returns The validated permission overlay
 * @throws Error if the value has an invalid structure, permission, pattern, or policy precedence
 */
export function parsePermissionsOverlay(raw: unknown): PermissionsOverlay {
  const root = asObject(raw, "overlay");

  if (root.policy !== undefined) {
    const policy = asObject(root.policy, "policy");
    if (policy.precedence !== undefined && policy.precedence !== "deny_over_allow") {
      throw new Error(
        `policy.precedence must be "deny_over_allow" (got ${JSON.stringify(policy.precedence)})`
      );
    }
  }

  const overlay: PermissionsOverlay = {};

  if (root.filesystem !== undefined) {
    const filesystem = asObject(root.filesystem, "filesystem");
    overlay.filesystem = {};
    if (filesystem.edit !== undefined)
      overlay.filesystem.edit = permission(filesystem.edit, "filesystem.edit");
    if (filesystem.write !== undefined)
      overlay.filesystem.write = permission(filesystem.write, "filesystem.write");
  }

  if (root.shell !== undefined) {
    const shell = asObject(root.shell, "shell");
    overlay.shell = {};
    if (shell.default !== undefined)
      overlay.shell.default = permission(shell.default, "shell.default");
    if (shell.allow !== undefined) overlay.shell.allow = patterns(shell.allow, "shell.allow");
    if (shell.deny !== undefined) overlay.shell.deny = patterns(shell.deny, "shell.deny");
  }

  return overlay;
}

/**
 * Ranks permission values by strictness so overlays can only ever tighten.
 * deny is strictest, then ask, then allow.
 */
const strictness: Record<PermissionValue, number> = { deny: 2, ask: 1, allow: 0 };

/**
 * Selects the more restrictive permission value.
 *
 * @param base - The existing permission value
 * @param overlay - The permission value to compare with the existing value
 * @returns The stricter permission value according to the `deny`, `ask`, and `allow` precedence order
 */
function stricter(base: PermissionValue, overlay: PermissionValue): PermissionValue {
  return strictness[overlay] > strictness[base] ? overlay : base;
}

/** Applies a blanket scalar restriction to every outcome in a path capability. */
function tightenCapability(
  base: CapabilityPermissions,
  overlay: PermissionValue
): CapabilityPermissions {
  if (overlay === "deny") {
    return { default: "deny", allow: [], ask: [], deny: [...base.deny] };
  }
  if (overlay === "ask") {
    return {
      default: stricter(base.default, overlay),
      allow: [],
      ask: [...new Set([...base.ask, ...base.allow])],
      deny: [...base.deny]
    };
  }
  return {
    default: base.default,
    allow: [...base.allow],
    ask: [...base.ask],
    deny: [...base.deny]
  };
}

/**
 * Merges an environment-specific permission overlay into a base permission set while preserving or tightening its restrictions.
 *
 * @param base - The base permission configuration
 * @param overlay - The optional permission changes to apply
 * @returns A new permission configuration with stricter permissions and merged shell patterns
 */
export function mergeOverlay(base: Permissions, overlay: PermissionsOverlay): Permissions {
  const merged: Permissions = {
    version: base.version,
    policy: { precedence: "deny_over_allow" },
    filesystem: { ...base.filesystem },
    shell: { ...base.shell, allow: [...base.shell.allow], deny: [...base.shell.deny] }
  };

  // Top-level v2 capability sections are carried through unchanged.
  if (base.network) merged.network = base.network;
  if (base.env) merged.env = base.env;
  if (base.mcp) merged.mcp = base.mcp;

  if (overlay.filesystem?.edit !== undefined) {
    merged.filesystem.edit = stricter(base.filesystem.edit, overlay.filesystem.edit);
    if (base.filesystem.read) {
      merged.filesystem.read = tightenCapability(base.filesystem.read, overlay.filesystem.edit);
    }
  }
  if (overlay.filesystem?.write !== undefined) {
    merged.filesystem.write = stricter(base.filesystem.write, overlay.filesystem.write);
    if (base.filesystem.writePaths) {
      merged.filesystem.writePaths = tightenCapability(
        base.filesystem.writePaths,
        overlay.filesystem.write
      );
    }
  }

  if (overlay.shell?.default !== undefined)
    merged.shell.default = stricter(base.shell.default, overlay.shell.default);

  // deny: union
  if (overlay.shell?.deny !== undefined) {
    merged.shell.deny = [...new Set([...base.shell.deny, ...overlay.shell.deny])];
  }

  // allow: intersection (overlay can only remove permissions)
  if (overlay.shell?.allow !== undefined) {
    const overlayAllow = new Set(overlay.shell.allow);
    merged.shell.allow = base.shell.allow.filter((pattern) => overlayAllow.has(pattern));
  }

  // Preserve the deny_over_allow invariant: anything newly denied must not
  // remain in the allow list.
  const denySet = new Set(merged.shell.deny);
  merged.shell.allow = merged.shell.allow.filter((pattern) => !denySet.has(pattern));

  return merged;
}

/**
 * Resolves the active environment name. An explicit value (from `--env`) wins;
 * otherwise `AGENTCTL_ENV` is used; otherwise CI is auto-detected from `CI` /
 * `GITHUB_ACTIONS`; otherwise defaults to `local`.
 */
export function resolveEnv(explicit?: string, env: NodeJS.ProcessEnv = process.env): string {
  if (explicit) return explicit;
  if (env.AGENTCTL_ENV) return env.AGENTCTL_ENV;
  if (env.CI === "true" || env.GITHUB_ACTIONS === "true") return "ci";
  return "local";
}

/**
 * Converts a glob pattern into an anchored regular expression source string.
 *
 * @param glob - The glob pattern, including optional `*` wildcards
 * @returns A regular expression source string that matches the entire input
 */
export function globToRegexSource(glob: string): string {
  return "^" + glob.replace(/[.+^${}()|[\\]\\]/g, "\\$&").replace(/\*/g, ".*") + "$";
}
