/** Canonical marker embedded in all generated files for detection by `agentctl scan`. */
export const GENERATED_MARKER = "@generated by agentctl — DO NOT EDIT";

export type PermissionValue = "allow" | "ask" | "deny";

export interface Permissions {
  policy: { precedence: "deny_over_allow" };
  filesystem: { edit: PermissionValue; write: PermissionValue };
  shell: { default: PermissionValue; allow: string[]; deny: string[] };
}

const values = new Set<PermissionValue>(["allow", "ask", "deny"]);

function asObject(value: unknown, label: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(
      `${label} must be an object.\n  Expected structure:\n    ${label}:\n      <key>: <value>`
    );
  }
  return value as Record<string, unknown>;
}

function permission(value: unknown, label: string): PermissionValue {
  if (typeof value !== "string" || !values.has(value as PermissionValue)) {
    throw new Error(`${label} must be one of: allow, ask, deny (got ${JSON.stringify(value)})`);
  }
  return value as PermissionValue;
}

function patterns(value: unknown, label: string): string[] {
  if (
    !Array.isArray(value) ||
    value.some((item) => typeof item !== "string" || item.length === 0)
  ) {
    throw new Error(
      `${label} must be an array of non-empty strings.\n  Expected structure:\n    ${label.split(".").pop()}:\n      - "pattern/*"`
    );
  }
  const result = value as string[];
  if (new Set(result).size !== result.length)
    throw new Error(`${label} contains duplicate patterns`);
  return result;
}

/** Validates the runtime-neutral source-of-truth permission format. */
export function parsePermissions(raw: unknown): Permissions {
  const root = asObject(raw, "permissions");
  const policy = asObject(root.policy, "policy");
  if (policy.precedence !== "deny_over_allow") {
    throw new Error(
      `policy.precedence must be "deny_over_allow" (got ${JSON.stringify(policy.precedence)})`
    );
  }
  const filesystem = asObject(root.filesystem, "filesystem");
  const shell = asObject(root.shell, "shell");
  const parsed: Permissions = {
    policy: { precedence: "deny_over_allow" },
    filesystem: {
      edit: permission(filesystem.edit, "filesystem.edit"),
      write: permission(filesystem.write, "filesystem.write")
    },
    shell: {
      default: permission(shell.default, "shell.default"),
      allow: patterns(shell.allow ?? [], "shell.allow"),
      deny: patterns(shell.deny ?? [], "shell.deny")
    }
  };
  const overlap = parsed.shell.allow.filter((pattern) => parsed.shell.deny.includes(pattern));
  if (overlap.length)
    throw new Error(`contradictory shell allow/deny patterns: ${overlap.join(", ")}`);
  return parsed;
}

export function globToRegexSource(glob: string): string {
  return "^" + glob.replace(/[.+^${}()|[\\]\\]/g, "\\$&").replace(/\*/g, ".*") + "$";
}
