import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { parse, stringify } from "yaml";
import { PermissionValue, GENERATED_MARKER } from "./permissions";

/** A runtime config detected on disk. */
export interface DetectedRuntime {
  name: string;
  path: string;
  shell: PermissionValue;
  allowPatterns: string[];
  denyPatterns: string[];
  filesystem?: { edit?: PermissionValue; write?: PermissionValue };
}

/** A conflict between two runtimes on the shell default mode. */
export interface Conflict {
  field: string;
  runtimes: { name: string; value: string }[];
  resolved: string;
}

/** Result of scanning the project root. */
export interface ScanResult {
  detected: DetectedRuntime[];
  conflicts: Conflict[];
  warnings: string[];
  configYaml: string;
  permissionsYaml: string;
}

/**
 * Check whether a raw config file was generated by agentctl.
 * All adapters emit `GENERATED_MARKER` in their output.
 * Legacy fallback: files generated before the marker was introduced may
 * contain older phrasing that still matches.
 */
export function isGeneratedFile(raw: string): boolean {
  // Canonical check — all current adapters emit this exact string.
  if (raw.includes(GENERATED_MARKER)) return true;
  // Legacy fallback for older generated files.
  if (raw.includes("Generated by: agentctl")) return true;
  if (raw.includes("generated by agentctl")) return true;
  return false;
}

/**
 * Convert a simple regex source (from globToRegexSource) back to a glob.
 * If the result still contains regex-specific characters, prefixes with a
 * comment marker to flag for manual review.
 */
export function regexSourceToGlob(src: string): string {
  let glob = src;
  // Strip anchors
  if (glob.startsWith("^")) glob = glob.slice(1);
  if (glob.endsWith("$")) glob = glob.slice(0, -1);
  // Convert .* back to *
  glob = glob.replace(/\.\*/g, "*");
  // Convert .+ back to *
  glob = glob.replace(/\.\+/g, "*");
  // Unescape common characters
  glob = glob.replace(/\\([.+^${}()|[\]\\/])/g, "$1");

  // Check if the result still contains regex-specific chars that indicate
  // the pattern couldn't be cleanly converted to a glob
  if (/\(\?|\||\[.*\]/.test(glob) || /\{[^,}]*\|/.test(glob)) {
    return `# regex: ${src}\n${glob}`;
  }

  return glob;
}

/**
 * Parse `.claude/settings.json` and extract permissions.
 */
function parseClaude(raw: string): DetectedRuntime {
  const parsed = JSON.parse(raw) as {
    permissions?: { allow?: string[]; deny?: string[] };
  };
  const perms = parsed.permissions ?? {};
  const allowList = perms.allow ?? [];
  const denyList = perms.deny ?? [];

  const allow = allowList
    .filter((p: string) => p.startsWith("Bash(") && p.endsWith(")"))
    .map((p: string) => p.slice(5, -1));
  const deny = denyList
    .filter((p: string) => p.startsWith("Bash(") && p.endsWith(")"))
    .map((p: string) => p.slice(5, -1));

  // Extract filesystem permissions from bare "Edit" / "Write" entries
  const filesystem: { edit?: PermissionValue; write?: PermissionValue } = {};

  if (allowList.includes("Edit")) {
    filesystem.edit = "allow";
  } else if (denyList.includes("Edit")) {
    filesystem.edit = "deny";
  } else {
    filesystem.edit = "ask";
  }

  if (allowList.includes("Write")) {
    filesystem.write = "allow";
  } else if (denyList.includes("Write")) {
    filesystem.write = "deny";
  } else {
    filesystem.write = "ask";
  }

  // Claude's shell mode is "ask" by default (it prompts for each command)
  const shell: PermissionValue = "ask";

  return {
    name: "claude",
    path: ".claude/settings.json",
    shell,
    allowPatterns: allow,
    denyPatterns: deny,
    filesystem
  };
}

/**
 * Parse codex config. Supports both `.codex/config.toml` and top-level `codex.json`.
 */
function parseCodex(raw: string, path: string): DetectedRuntime {
  let shell: PermissionValue = "ask";
  const allowPatterns: string[] = [];
  const denyPatterns: string[] = [];

  if (path.endsWith(".toml")) {
    // Simple TOML parsing for the fields we care about
    const approvalMatch = raw.match(/approval_policy\s*=\s*"([^"]+)"/);
    if (approvalMatch) {
      const policy = approvalMatch[1];
      if (policy === "auto") shell = "allow";
      else if (policy === "never") shell = "deny";
      else shell = "ask";
    }
  } else {
    // codex.json format
    const parsed = JSON.parse(raw) as {
      approval_policy?: string;
      shell?: { allow?: string[]; deny?: string[] };
    };
    if (parsed.approval_policy === "auto") shell = "allow";
    else if (parsed.approval_policy === "never") shell = "deny";
    else shell = "ask";
    if (parsed.shell) {
      allowPatterns.push(...(parsed.shell.allow ?? []));
      denyPatterns.push(...(parsed.shell.deny ?? []));
    }
  }

  return { name: "codex", path, shell, allowPatterns, denyPatterns };
}

/**
 * Parse the codex hook script to extract allow/deny regex patterns and convert back to globs.
 */
function parseCodexHook(raw: string): { allow: string[]; deny: string[] } {
  const allow: string[] = [];
  const deny: string[] = [];

  const denyMatch = raw.match(/DENY_PATTERNS\s*=\s*\[([^\]]*)\]/s);
  if (denyMatch) {
    const patterns = denyMatch[1].match(/"([^"]+)"/g);
    if (patterns) deny.push(...patterns.map((p) => regexSourceToGlob(p.slice(1, -1))));
  }

  const allowMatch = raw.match(/ALLOW_PATTERNS\s*=\s*\[([^\]]*)\]/s);
  if (allowMatch) {
    const patterns = allowMatch[1].match(/"([^"]+)"/g);
    if (patterns) allow.push(...patterns.map((p) => regexSourceToGlob(p.slice(1, -1))));
  }

  return { allow, deny };
}

/**
 * Parse `.kiro/settings/permissions.yaml` — Kiro's capability-based rules format.
 *
 * Rules array with: { capability, effect, match? }
 * - Shell rules: capability="shell", patterns in match[]
 * - Shell default: catch-all shell rule (no match or match:["**"])
 * - fs_write: capability="fs_write", effect = the filesystem write permission
 */
function parseKiro(raw: string): DetectedRuntime {
  const parsed = parse(raw) as {
    rules?: Array<{ capability: string; effect: string; match?: string[] }>;
  };
  const rules = parsed.rules ?? [];

  let shell: PermissionValue = "ask";
  const allowPatterns: string[] = [];
  const denyPatterns: string[] = [];
  const filesystem: { edit?: PermissionValue; write?: PermissionValue } = {};

  for (const rule of rules) {
    const effect = rule.effect as PermissionValue;

    if (rule.capability === "shell") {
      const hasMatch = rule.match && rule.match.length > 0;
      const isCatchAll = !hasMatch || (rule.match!.length === 1 && rule.match![0] === "**");

      if (!hasMatch || isCatchAll) {
        // This is the default shell posture
        shell = effect;
      } else if (effect === "deny") {
        denyPatterns.push(...rule.match!);
      } else if (effect === "allow") {
        allowPatterns.push(...rule.match!);
      }
    } else if (rule.capability === "fs_write") {
      filesystem.write = effect;
    } else if (rule.capability === "fs_read") {
      // fs_read maps to edit permission in our model
      filesystem.edit = effect;
    }
  }

  return {
    name: "kiro",
    path: ".kiro/settings/permissions.yaml",
    shell,
    allowPatterns,
    denyPatterns,
    filesystem
  };
}

/**
 * Parse `.opencode/opencode.json` — OpenCode's permission format.
 *
 * JSON with: { permission: { edit, write, bash: { "*": default, ...patterns } } }
 */
function parseOpenCode(raw: string): DetectedRuntime {
  const parsed = JSON.parse(raw) as {
    permission?: {
      edit?: string;
      write?: string;
      bash?: Record<string, string>;
    };
  };
  const perm = parsed.permission ?? {};
  const bash = perm.bash ?? {};

  // The "*" key is the shell default
  let shell: PermissionValue = "ask";
  if (bash["*"]) {
    const val = bash["*"];
    if (val === "allow" || val === "ask" || val === "deny") {
      shell = val;
    }
  }

  const allowPatterns: string[] = [];
  const denyPatterns: string[] = [];

  for (const [pattern, value] of Object.entries(bash)) {
    if (pattern === "*") continue;
    if (value === "allow") allowPatterns.push(pattern);
    else if (value === "deny") denyPatterns.push(pattern);
  }

  const filesystem: { edit?: PermissionValue; write?: PermissionValue } = {};
  if (perm.edit && (perm.edit === "allow" || perm.edit === "ask" || perm.edit === "deny")) {
    filesystem.edit = perm.edit as PermissionValue;
  }
  if (perm.write && (perm.write === "allow" || perm.write === "ask" || perm.write === "deny")) {
    filesystem.write = perm.write as PermissionValue;
  }

  return {
    name: "opencode",
    path: ".opencode/opencode.json",
    shell,
    allowPatterns,
    denyPatterns,
    filesystem
  };
}

/**
 * Parse `.cursor/rules/agentctl-permissions/RULE.md` — Cursor's MDC rule format.
 *
 * Extracts:
 * - Default policy from `Default policy: <value>` line
 * - Denied patterns from `### Denied` section
 * - Allowed patterns from `### Allowed` section
 * - Filesystem from `- File editing: <value>` and `- File creation/write: <value>`
 */
function parseCursor(raw: string): DetectedRuntime {
  let shell: PermissionValue = "ask";
  const allowPatterns: string[] = [];
  const denyPatterns: string[] = [];
  const filesystem: { edit?: PermissionValue; write?: PermissionValue } = {};

  // Extract default policy
  const defaultMatch = raw.match(/Default policy:\s*(allow|ask|deny)/);
  if (defaultMatch) {
    shell = defaultMatch[1] as PermissionValue;
  }

  // Extract filesystem permissions
  const editMatch = raw.match(/- File editing:\s*(allow|ask|deny)/);
  if (editMatch) {
    filesystem.edit = editMatch[1] as PermissionValue;
  }

  const writeMatch = raw.match(/- File creation\/write:\s*(allow|ask|deny)/);
  if (writeMatch) {
    filesystem.write = writeMatch[1] as PermissionValue;
  }

  // Extract denied patterns from ### Denied section
  const deniedSection = raw.match(/### Denied[^\n]*\n([\s\S]*?)(?=\n###|\n##|$)/);
  if (deniedSection) {
    const patternMatches = deniedSection[1].matchAll(/- `([^`]+)`/g);
    for (const m of patternMatches) {
      denyPatterns.push(m[1]);
    }
  }

  // Extract allowed patterns from ### Allowed section
  const allowedSection = raw.match(/### Allowed[^\n]*\n([\s\S]*?)(?=\n###|\n##|$)/);
  if (allowedSection) {
    const patternMatches = allowedSection[1].matchAll(/- `([^`]+)`/g);
    for (const m of patternMatches) {
      allowPatterns.push(m[1]);
    }
  }

  return {
    name: "cursor",
    path: ".cursor/rules/agentctl-permissions/RULE.md",
    shell,
    allowPatterns,
    denyPatterns,
    filesystem
  };
}

/** Resolve a permission conflict. Prefer most restrictive: deny > ask > allow. */
function resolveMostRestrictive(values: PermissionValue[]): PermissionValue {
  if (values.includes("deny")) return "deny";
  if (values.includes("ask")) return "ask";
  return "allow";
}

/**
 * Scan a project root for known runtime config files and produce a merged `.ai/` config.
 */
export async function scan(root: string): Promise<ScanResult> {
  const detected: DetectedRuntime[] = [];
  const warnings: string[] = [];

  // Detect Claude
  const claudePath = resolve(root, ".claude/settings.json");
  if (existsSync(claudePath)) {
    const raw = await readFile(claudePath, "utf8");
    if (isGeneratedFile(raw)) {
      warnings.push("claude: .claude/settings.json appears to be generated by agentctl");
    }
    detected.push(parseClaude(raw));
  }

  // Detect Codex — try .codex/config.toml first, then codex.json
  const codexTomlPath = resolve(root, ".codex/config.toml");
  const codexJsonPath = resolve(root, "codex.json");
  if (existsSync(codexTomlPath)) {
    const raw = await readFile(codexTomlPath, "utf8");
    if (isGeneratedFile(raw)) {
      warnings.push("codex: .codex/config.toml appears to be generated by agentctl");
    }
    const result = parseCodex(raw, ".codex/config.toml");
    // Also try to read the hook for patterns
    const hookPath = resolve(root, ".codex/hooks/permission-policy.py");
    if (existsSync(hookPath)) {
      const hookRaw = await readFile(hookPath, "utf8");
      const hookPatterns = parseCodexHook(hookRaw);
      result.allowPatterns.push(...hookPatterns.allow);
      result.denyPatterns.push(...hookPatterns.deny);
    }
    detected.push(result);
  } else if (existsSync(codexJsonPath)) {
    const raw = await readFile(codexJsonPath, "utf8");
    if (isGeneratedFile(raw)) {
      warnings.push("codex: codex.json appears to be generated by agentctl");
    }
    detected.push(parseCodex(raw, "codex.json"));
  }

  // Detect Cursor
  const cursorPath = resolve(root, ".cursor/rules/agentctl-permissions/RULE.md");
  if (existsSync(cursorPath)) {
    const raw = await readFile(cursorPath, "utf8");
    if (isGeneratedFile(raw)) {
      warnings.push(
        "cursor: .cursor/rules/agentctl-permissions/RULE.md appears to be generated by agentctl"
      );
    }
    detected.push(parseCursor(raw));
  }

  // Detect Kiro
  const kiroPath = resolve(root, ".kiro/settings/permissions.yaml");
  if (existsSync(kiroPath)) {
    const raw = await readFile(kiroPath, "utf8");
    if (isGeneratedFile(raw)) {
      warnings.push("kiro: .kiro/settings/permissions.yaml appears to be generated by agentctl");
    }
    detected.push(parseKiro(raw));
  }

  // Detect OpenCode
  const opencodePath = resolve(root, ".opencode/opencode.json");
  if (existsSync(opencodePath)) {
    const raw = await readFile(opencodePath, "utf8");
    if (isGeneratedFile(raw)) {
      warnings.push("opencode: .opencode/opencode.json appears to be generated by agentctl");
    }
    detected.push(parseOpenCode(raw));
  }

  if (detected.length === 0) {
    return {
      detected: [],
      conflicts: [],
      warnings: [],
      configYaml: "",
      permissionsYaml: ""
    };
  }

  // Merge patterns with deduplication
  const allAllow = [...new Set(detected.flatMap((d) => d.allowPatterns))];
  const allDeny = [...new Set(detected.flatMap((d) => d.denyPatterns))];

  // Detect conflicts
  const conflicts: Conflict[] = [];
  const shellModes = detected.map((d) => d.shell);
  const uniqueModes = [...new Set(shellModes)];
  const resolvedShell = resolveMostRestrictive(shellModes);
  if (uniqueModes.length > 1) {
    conflicts.push({
      field: "shell.default",
      runtimes: detected.map((d) => ({ name: d.name, value: d.shell })),
      resolved: resolvedShell
    });
  }

  // Derive filesystem permissions from detected runtimes (most restrictive wins)
  const editValues: PermissionValue[] = [];
  const writeValues: PermissionValue[] = [];
  for (const d of detected) {
    if (d.filesystem?.edit) editValues.push(d.filesystem.edit);
    if (d.filesystem?.write) writeValues.push(d.filesystem.write);
  }
  const resolvedEdit: PermissionValue =
    editValues.length > 0 ? resolveMostRestrictive(editValues) : "allow";
  const resolvedWrite: PermissionValue =
    writeValues.length > 0 ? resolveMostRestrictive(writeValues) : "allow";

  // Detect filesystem conflicts
  const uniqueEdit = [...new Set(editValues)];
  if (uniqueEdit.length > 1) {
    conflicts.push({
      field: "filesystem.edit",
      runtimes: detected
        .filter((d) => d.filesystem?.edit)
        .map((d) => ({ name: d.name, value: d.filesystem!.edit! })),
      resolved: resolvedEdit
    });
  }
  const uniqueWrite = [...new Set(writeValues)];
  if (uniqueWrite.length > 1) {
    conflicts.push({
      field: "filesystem.write",
      runtimes: detected
        .filter((d) => d.filesystem?.write)
        .map((d) => ({ name: d.name, value: d.filesystem!.write! })),
      resolved: resolvedWrite
    });
  }

  // Build runtimes map — enable detected runtimes
  const runtimes: Record<string, { enabled: boolean }> = {
    claude: { enabled: detected.some((d) => d.name === "claude") },
    codex: { enabled: detected.some((d) => d.name === "codex") },
    cursor: { enabled: detected.some((d) => d.name === "cursor") },
    kiro: { enabled: detected.some((d) => d.name === "kiro") },
    opencode: { enabled: detected.some((d) => d.name === "opencode") }
  };

  const configObj = {
    project: { name: "__PROJECT_NAME__" },
    runtimes,
    sync: { permissions: true },
    files: { permissions: ".ai/permissions.yaml" }
  };

  const permissionsObj = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: resolvedEdit, write: resolvedWrite },
    shell: {
      default: resolvedShell,
      allow: allAllow,
      deny: allDeny
    }
  };

  const configYaml = stringify(configObj, { lineWidth: 0 });
  const permissionsYaml = stringify(permissionsObj, { lineWidth: 0 });

  return { detected, conflicts, warnings, configYaml, permissionsYaml };
}
