import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { stringify } from "yaml";
import { PermissionValue, GENERATED_MARKER } from "./permissions";
import { adapters } from "./adapter";
import { parseCodexHook } from "./adapters/codex";

/** A runtime config detected on disk. */
export interface DetectedRuntime {
  name: string;
  path: string;
  shell: PermissionValue;
  allowPatterns: string[];
  denyPatterns: string[];
  filesystem?: { edit?: PermissionValue; write?: PermissionValue };
}

/** A conflict between two runtimes on the shell default mode. */
export interface Conflict {
  field: string;
  runtimes: { name: string; value: string }[];
  resolved: string;
}

/** Result of scanning the project root. */
export interface ScanResult {
  detected: DetectedRuntime[];
  conflicts: Conflict[];
  warnings: string[];
  configYaml: string;
  permissionsYaml: string;
}

/**
 * Check whether a raw config file was generated by agentctl.
 * All adapters emit `GENERATED_MARKER` in their output.
 */
export function isGeneratedFile(raw: string): boolean {
  if (raw.includes(GENERATED_MARKER)) return true;
  if (raw.includes("Generated by: agentctl")) return true;
  if (raw.includes("generated by agentctl")) return true;
  return false;
}

/**
 * Convert a simple regex source (from globToRegexSource) back to a glob.
 */
export function regexSourceToGlob(src: string): string {
  let glob = src;
  if (glob.startsWith("^")) glob = glob.slice(1);
  if (glob.endsWith("$")) glob = glob.slice(0, -1);
  glob = glob.replace(/\.\*/g, "*");
  glob = glob.replace(/\.\+/g, "*");
  glob = glob.replace(/\\([.+^${}()|[\]\\/])/g, "$1");

  if (/\(\?|\||\[.*\]/.test(glob) || /\{[^,}]*\|/.test(glob)) {
    return `# regex: ${src}\n${glob}`;
  }

  return glob;
}

/** Resolve a permission conflict. Prefer most restrictive: deny > ask > allow. */
function resolveMostRestrictive(values: PermissionValue[]): PermissionValue {
  if (values.includes("deny")) return "deny";
  if (values.includes("ask")) return "ask";
  return "allow";
}

/**
 * Scan a project root for known runtime config files and produce a merged `.ai/` config.
 * Iterates over all registered adapters to detect and parse existing configs.
 */
export async function scan(root: string): Promise<ScanResult> {
  const detected: DetectedRuntime[] = [];
  const warnings: string[] = [];

  for (const adapter of adapters) {
    // Special handling for codex: try .codex/config.toml first, then codex.json
    if (adapter.name === "codex") {
      const tomlPath = resolve(root, ".codex/config.toml");
      const jsonPath = resolve(root, "codex.json");
      if (existsSync(tomlPath)) {
        const raw = await readFile(tomlPath, "utf8");
        if (isGeneratedFile(raw)) {
          warnings.push("codex: .codex/config.toml appears to be generated by agentctl");
        }
        const result = adapter.parse(raw, ".codex/config.toml");
        // Also try to read the hook for patterns
        const hookPath = resolve(root, ".codex/hooks/permission-policy.py");
        if (existsSync(hookPath)) {
          const hookRaw = await readFile(hookPath, "utf8");
          const hookPatterns = parseCodexHook(hookRaw);
          result.allowPatterns.push(...hookPatterns.allow);
          result.denyPatterns.push(...hookPatterns.deny);
        }
        detected.push(result);
      } else if (existsSync(jsonPath)) {
        const raw = await readFile(jsonPath, "utf8");
        if (isGeneratedFile(raw)) {
          warnings.push("codex: codex.json appears to be generated by agentctl");
        }
        detected.push(adapter.parse(raw, "codex.json"));
      }
      continue;
    }

    // Generic path: use the first path in the adapter's paths list for detection
    const primaryPath = adapter.paths[0];
    const fullPath = resolve(root, primaryPath);
    if (existsSync(fullPath)) {
      const raw = await readFile(fullPath, "utf8");
      if (isGeneratedFile(raw)) {
        warnings.push(`${adapter.name}: ${primaryPath} appears to be generated by agentctl`);
      }
      detected.push(adapter.parse(raw, primaryPath));
    }
  }

  if (detected.length === 0) {
    return {
      detected: [],
      conflicts: [],
      warnings: [],
      configYaml: "",
      permissionsYaml: ""
    };
  }

  // Merge patterns with deduplication
  const allAllow = [...new Set(detected.flatMap((d) => d.allowPatterns))];
  const allDeny = [...new Set(detected.flatMap((d) => d.denyPatterns))];

  // Detect conflicts
  const conflicts: Conflict[] = [];
  const shellModes = detected.map((d) => d.shell);
  const uniqueModes = [...new Set(shellModes)];
  const resolvedShell = resolveMostRestrictive(shellModes);
  if (uniqueModes.length > 1) {
    conflicts.push({
      field: "shell.default",
      runtimes: detected.map((d) => ({ name: d.name, value: d.shell })),
      resolved: resolvedShell
    });
  }

  // Derive filesystem permissions from detected runtimes (most restrictive wins)
  const editValues: PermissionValue[] = [];
  const writeValues: PermissionValue[] = [];
  for (const d of detected) {
    if (d.filesystem?.edit) editValues.push(d.filesystem.edit);
    if (d.filesystem?.write) writeValues.push(d.filesystem.write);
  }
  const resolvedEdit: PermissionValue =
    editValues.length > 0 ? resolveMostRestrictive(editValues) : "allow";
  const resolvedWrite: PermissionValue =
    writeValues.length > 0 ? resolveMostRestrictive(writeValues) : "allow";

  // Detect filesystem conflicts
  const uniqueEdit = [...new Set(editValues)];
  if (uniqueEdit.length > 1) {
    conflicts.push({
      field: "filesystem.edit",
      runtimes: detected
        .filter((d) => d.filesystem?.edit)
        .map((d) => ({ name: d.name, value: d.filesystem!.edit! })),
      resolved: resolvedEdit
    });
  }
  const uniqueWrite = [...new Set(writeValues)];
  if (uniqueWrite.length > 1) {
    conflicts.push({
      field: "filesystem.write",
      runtimes: detected
        .filter((d) => d.filesystem?.write)
        .map((d) => ({ name: d.name, value: d.filesystem!.write! })),
      resolved: resolvedWrite
    });
  }

  // Build runtimes map — enable detected runtimes
  const runtimes: Record<string, { enabled: boolean }> = {};
  for (const adapter of adapters) {
    runtimes[adapter.name] = { enabled: detected.some((d) => d.name === adapter.name) };
  }

  const configObj = {
    project: { name: "__PROJECT_NAME__" },
    runtimes,
    sync: { permissions: true },
    files: { permissions: ".ai/permissions.yaml" }
  };

  const permissionsObj = {
    policy: { precedence: "deny_over_allow" },
    filesystem: { edit: resolvedEdit, write: resolvedWrite },
    shell: {
      default: resolvedShell,
      allow: allAllow,
      deny: allDeny
    }
  };

  const configYaml = stringify(configObj, { lineWidth: 0 });
  const permissionsYaml = stringify(permissionsObj, { lineWidth: 0 });

  return { detected, conflicts, warnings, configYaml, permissionsYaml };
}
